language: php

php:
  - 5.4
  - 5.5

before_script:
  - sudo apt-get phantomjs
  - npm install
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev

script:
  - ./vendor/bin/phpcs --standard=phpcs.xml ./src/
  - ./vendor/bin/phpcs --standard=phpcs.xml ./tests/
  - ./vendor/bin/phpmd ./src/ text phpmd.xml
  - ./vendor/bin/phpmd ./tests/ text phpmd.xml
  - ./vendor/bin/parallel-lint ./src/
  - ./vendor/bin/parallel-lint ./tests/
  - ./vendor/bin/phpunit
  - grunt travis --verbose