language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

node_js:
  - 0.10
  - 5.0

before_script:
  - mkdir -p build/logs
  - npm install
  - travis_retry composer self-update
  - travis_retry composer install --prefer-source --no-interaction

script:
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then ./vendor/bin/phpcs --standard=phpcs.xml ./src/; fi;'
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then ./vendor/bin/phpcs --standard=phpcs.xml ./tests/; fi;'
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then ./vendor/bin/phpmd ./src/ text phpmd.xml; fi;'
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then ./vendor/bin/phpmd ./tests/ text phpmd.xml; fi;'
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then ./vendor/bin/parallel-lint ./src/; fi;'
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then ./vendor/bin/parallel-lint ./tests/; fi;'
  - ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml
  - ./node_modules/.bin/grunt travis --verbose

matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true